db:
  image: postgres:11
  ports:
    - '5433:5432'
  environment:
    POSTGRES_DB: minimalist

# test image, because typeorm migrations require the db to exist in order to work
db_test:
  image: postgres:11
  ports:
    - '5436:5432'
  environment:
    POSTGRES_DB: minimalist_test
