version: '3.1'

services:
  api:
    container_name: api
    build:
      context: ./
      args:
        - NODE_ENV=development
        - PORT=3000
    ports:
      - '3000:3000'
      - '5858:5858'
      - '9229:9229'
    volumes:
      - .:/opt/app:delegated
      # this is a workaround to prevent host node_modules from accidently getting mounted in container
      # in case you want to use node/npm both outside container for test/lint etc. and also inside container
      # this will overwrite the default node_modules dir in container so it won't conflict with our
      # /opt/node_modules location. Thanks to PR from @brnluiz
      - notused:/opt/app/node_modules
    environment:
      - NODE_ENV=development
      - PGHOST=docker.for.mac.localhost

volumes:
  notused:
